name: Tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: go get .

      - name: Run tests
        run: go test